import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        WebSocket: "readonly",
        location: "readonly",
        history: "readonly",
        navigator: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        self: "readonly",
        caches: "readonly",
        clients: "readonly",
        crypto: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        AudioContext: "readonly",
        MediaRecorder: "readonly",
        SpeechRecognition: "readonly",
        webkitSpeechRecognition: "readonly",
        speechSynthesis: "readonly",
        SpeechSynthesisUtterance: "readonly",
        AbortController: "readonly",
        Image: "readonly",
        Audio: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        performance: "readonly",
        // Avatar globals (from avatar.js)
        setAvatarState: "readonly",
        setAvatarConnection: "readonly",
        initAvatarScene: "readonly",
        onAvatarResize: "readonly",
        loadTaskBadge: "readonly",
        // Node globals
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        // External libraries
        SimpleWebAuthnBrowser: "readonly",
        THREE: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      semi: ["error", "always"],
      eqeqeq: ["error", "smart"],
      "no-var": "warn",
      "prefer-const": "warn",
    },
  },
  {
    ignores: ["node_modules/**", "public/js/**"],
  },
];
